# Get gcc from Docker Hub
FROM gcc:4.9

# Set proxy server variables
#ENV http_proxy http://user:password@host:port
#ENV https_proxy http://user:password@host:port

# Copy the current folder with the source code to the docker directory
#COPY . /usr/src

# Specify the working directory
#WORKDIR /usr/src

# Use GCC to compile the hello.cpp source file
#RUN g++ -o hello hello.cpp

# Run the programm
#CMD ["./hello"]
